### ISSUE TITLE
Still not fully working after update

### ISSUE THREAD

**Issue by beaubeire** [BrandonWill/GrepolisBot#8]
Issues:

- Qeue doesn't show towns.
- If you set farming mood at 100, it doesn't demand, instead it loots the farms. Which drop the farms their mood which i don't like

**Comment by BrandonWill** [comment]
Fun fact, the queue not showing towns was always a bug since the graphics rework. You just never noticed it because it had all your towns loaded already before ^.^. That one was real fun trying to figure out. This will now update correctly for first run users, yay!

Other bug should now be fixed as well.
